Updated pipe to get logs

diff --git a/.github/workflows/build.yml b/.github/workflows/build.yml
--- a/.github/workflows/build.yml
+++ b/.github/workflows/build.yml
@@ -77,6 +77,9 @@ jobs:
         runs-on: ubuntu-latest
         needs: prettier
         steps:
+            - name: Check node version
+              run: node -v
+
             - name: Checkout repo
               uses: actions/checkout@v4
 
@@ -96,7 +99,7 @@ jobs:
               run: |
                   npx http-server storybook-static --port 6006 --silent &
                   npx wait-on http://localhost:6006
-                  npm run test-storybook || (echo "❌ Storybook tests failed" && exit 1)
+                  DEBUG=storybook* npm run test-storybook || (echo "❌ Storybook tests failed" && exit 1)
 
             - name: Show Storybook Logs on Failure
               if: failure()
