Added node version in key

diff --git a/.github/workflows/build.yml b/.github/workflows/build.yml
--- a/.github/workflows/build.yml
+++ b/.github/workflows/build.yml
@@ -25,7 +25,7 @@ jobs:
                       ~/.npm
                       node_modules
                       ~/.cache/ms-playwright
-                  key: ${{ runner.os }}-node-${{ hashFiles('package-lock.json') }}-playwright
+                  key: ${{ runner.os }}-node-22-${{ hashFiles('package-lock.json') }}-playwright
 
             - name: Install npm dependencies
               run: npm install
@@ -47,7 +47,7 @@ jobs:
                   path: |
                       ~/.npm
                       node_modules
-                  key: ${{ runner.os }}-node-${{ hashFiles('package-lock.json') }}-playwright
+                  key: ${{ runner.os }}-node-22-${{ hashFiles('package-lock.json') }}-playwright
 
             - name: Check code formatting with Prettier
               run: npx prettier --check .
@@ -67,7 +67,7 @@ jobs:
                       ~/.npm
                       node_modules
                       ~/.cache/ms-playwright
-                  key: ${{ runner.os }}-node-${{ hashFiles('package-lock.json') }}-playwright
+                  key: ${{ runner.os }}-node-22-${{ hashFiles('package-lock.json') }}-playwright
 
             - name: Run Karma tests (Headless Chrome)
               run: npm run test -- --watch=false --browsers=ChromeHeadless
@@ -77,9 +77,6 @@ jobs:
         runs-on: ubuntu-latest
         needs: prettier
         steps:
-            - name: Check node version
-              run: node -v
-
             - name: Checkout repo
               uses: actions/checkout@v4
 
@@ -90,7 +87,7 @@ jobs:
                       ~/.npm
                       node_modules
                       ~/.cache/ms-playwright
-                  key: ${{ runner.os }}-node-${{ hashFiles('package-lock.json') }}-playwright
+                  key: ${{ runner.os }}-node-22-${{ hashFiles('package-lock.json') }}-playwright
 
             - name: Build Storybook
               run: npm run build-storybook --quiet > storybook.log 2>&1
@@ -99,7 +96,7 @@ jobs:
               run: |
                   npx http-server storybook-static --port 6006 --silent &
                   npx wait-on http://localhost:6006
-                  DEBUG=storybook* npm run test-storybook || (echo "❌ Storybook tests failed" && exit 1)
+                  npm run test-storybook || (echo "❌ Storybook tests failed" && exit 1)
 
             - name: Show Storybook Logs on Failure
               if: failure()
